version: "3"

networks:
  proxy:
    external: true

services:
  poe-bot:
      container_name: poe-bot
      image: ghcr.io/nerdneilsfield/poe-api-bots:latest
      restart: always
      networks:
        - proxy
      volumes:
        - ./configs/config.toml:/app/configs/config.toml
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - "traefik.http.routers.poe-bot.entrypoints=http"
        - "traefik.http.routers.poe-bot.rule=Host(`example.com`)"
        - "traefik.http.routers.poe-bot.middlewares=https-redirect@docker"
        - traefik.http.routers.poe-bot-secure.entrypoints=https
        - traefik.http.routers.poe-bot-secure.rule=Host(`example.com`)"
        - traefik.http.routers.poe-bot-secure.tls=true
        - traefik.http.routers.poe-bot-secure.tls.certresolver=cloudflare
        - traefik.http.services.poe-bot.loadbalancer.server.port=80
