name: Build and Push Docker Image

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "CHANGELOG"
      - "docker/*"
      - "configs/confg.example.toml"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "CHANGELOG"
      - "docker/*"
      - "configs/confg.example.toml"
    branches:
      - master

env:
  IMAGE_NAME: poe-api-bots

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: nerdneilsfield
      #     password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: nerdneils
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/nerdneils/${{ env.IMAGE_NAME }}:latest
